import os
import json
from datetime import date
from sqlalchemy.orm import Session
from fastapi import HTTPException
from google import genai  # <-- NEW SDK IMPORT

from app.models.daily_report import DailyReport

# Safely load the API key from your .env file
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

def generate_daily_safety_report(db: Session, target_date: date) -> DailyReport:
    """
    Phase 9 Service: Generates a natural-language report using the Gemini SLM.
    Strictly uses the Phase 8 pre-aggregated data to prevent AI hallucinations.
    """
    # 1. Retrieve the existing DailyReport generated by Phase 8
    report = db.query(DailyReport).filter(DailyReport.report_date == target_date).first()
    
    if not report:
        raise HTTPException(
            status_code=404, 
            detail=f"No Phase 8 data found for {target_date}. Run analytics first."
        )
        
    if not GEMINI_API_KEY:
        raise HTTPException(
            status_code=500, 
            detail="GEMINI_API_KEY is not configured in the environment."
        )

    # 2. Prepare the highly constrained Prompt (The Brain)
    prompt = f"""
    You are a professional construction safety compliance reporting assistant.
    Your exact task is to convert the following verified system data into a concise, factual daily safety report paragraph.

    RULES - YOU MUST STRICTLY OBEY:
    1. DO NOT invent, hallucinate, or assume any worker names, injuries, weather conditions, or disciplinary actions.
    2. DO NOT recalculate the compliance rate or event counts. Use the provided numbers exactly.
    3. ONLY report on the facts provided in the JSON data below.
    4. If total events and attendance are 0, state clearly that no attendance or PPE activity was recorded today.
    5. The report should be a single, professional paragraph.

    VERIFIED SYSTEM DATA FOR {target_date}:
    Attendance Summary: {json.dumps(report.attendance_summary)}
    PPE Violations Summary: {json.dumps(report.ppe_summary)}
    Global Compliance Rate: {report.compliance_rate}%
    """

    # 3. Call the Gemini API using the modern SDK and active model
    try:
        # Initialize the modern SDK client
        client = genai.Client(api_key=GEMINI_API_KEY)
        
        # Using gemini-3.6-flash as the current stable model
        response = client.models.generate_content(
            model='gemini-3.6-flash',
            contents=prompt
        )
        
        # Robustness Check: Prevent saving empty reports if the AI glitches
        if not response.text or not response.text.strip():
            raise HTTPException(
                status_code=502,
                detail="SLM returned an empty report."
            )
            
        report_text = response.text.strip()
    except Exception as e:
        # Phase 9 Requirement: Clean failure handling (Do not silently pretend it worked)
        raise HTTPException(status_code=502, detail=f"SLM API Generation Failed: {str(e)}")
        
    # 4. Save the generated text to Phase 9's specific column
    report.report_content = report_text
    db.commit()
    db.refresh(report)
    
    return report