"""initial database schema

Revision ID: 84c2666ad27e
Revises: 
Create Date: 2026-08-12 17:39:40.436287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '84c2666ad27e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('daily_reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attendance_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ppe_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compliance_rate', sa.Float(), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('video_sources',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('workers',
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_table('attendance_records',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('worker_id', 'date', name='uq_attendance_worker_date')
    )
    op.create_table('face_embeddings',
    sa.Column('embedding_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('embedding_id')
    )
    op.create_table('ppe_compliance_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('helmet_detected', sa.Boolean(), nullable=False),
    sa.Column('vest_detected', sa.Boolean(), nullable=False),
    sa.Column('compliance_status', sa.Enum('FULL_PPE', 'HELMET_MISSING', 'VEST_MISSING', 'NO_PPE', name='ppe_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video_sources.video_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ppe_compliance_logs')
    op.drop_table('face_embeddings')
    op.drop_table('attendance_records')
    op.drop_table('workers')
    op.drop_table('video_sources')
    op.drop_table('daily_reports')
    op.drop_table('administrators')
    # ### end Alembic commands ###
