"""update_ppe_timestamps

Revision ID: a6b22d9e7c6e
Revises: 84c2666ad27e
Create Date: 2026-09-12 16:32:38.596835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b22d9e7c6e'
down_revision: Union[str, Sequence[str], None] = '84c2666ad27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppe_compliance_logs', sa.Column('start_timestamp', sa.Float(), nullable=False))
    op.add_column('ppe_compliance_logs', sa.Column('end_timestamp', sa.Float(), nullable=True))
    op.drop_column('ppe_compliance_logs', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppe_compliance_logs', sa.Column('timestamp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('ppe_compliance_logs', 'end_timestamp')
    op.drop_column('ppe_compliance_logs', 'start_timestamp')
    # ### end Alembic commands ###
